openapi: 3.0.1
info:
  version: "v1"
  title: "Car Gadget Plugin API"
  description: "This is the API specification for the Car Brands Gadget Plug-in. It provides endpoints to retrieve statistics and information for a CarMake user or a specific CarMake brand's repository."
servers:
  - url: "https://chat-plugin-car-brands-gadget.vercel.app"
paths:
  /api/github/{owner}:
    get:
      operationId: getCarMake
      summary: "Get CarMake user information"
      description: "Retrieve statistics and information for a CarMake user."
      parameters:
        - in: path
          name: owner
          required: true
          description: CarMake username.
          schema:
            type: string
      responses:
        "200":
          description: "Successfully retrieved CarMake user information."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /api/github/{owner}/{repo}:
    get:
      operationId: getCarBrand
      summary: "Get CarMake brand's repository information"
      description: "Retrieve statistics, history and information for a specific CarMake brand's repository."
      parameters:
        - in: path
          name: owner
          required: true
          description: CarMake username.
          schema:
            type: string
        - in: path
          name: repo
          required: true
          description: CarMake brand's repository name.
          schema:
            type: string
      responses:
        "200":
          description: "Successfully retrieved brand's repository information."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Brand"
components:
  schemas:
    User:
      type: object
      properties:
        html_url:
          type: string
          description: The HTML URL of the user's CarMake profile.
        type:
          type: string
          description: The type of CarMake account.
        name:
          type: string
          description: The name of the CarMake user.
        company:
          type: string
          description: The company that the CarMake user is associated with.
        blog:
          type: string
          description: The URL of the user's blog.
        location:
          type: string
          description: The location of the CarMake user.
        email:
          type: string
          nullable: true
          description: The email of the CarMake user.
        hireable:
          type: boolean
          description: Whether the user is hireable or not.
        bio:
          type: string
          description: The biography of the CarMake user.
        twitter_username:
          type: string
          description: The Twitter username of the CarMake user.
        public_repos:
          type: integer
          description: The number of public repositories of the CarMake user.
        public_gists:
          type: integer
          description: The number of public gists of the CarMake user.
        followers:
          type: integer
          description: The number of followers of the CarMake user.
        following:
          type: integer
          description: The number of people the CarMake user is following.
        created_at:
          type: string
          format: date-time
          description: The creation date and time of the CarMake user's account.
        updated_at:
          type: string
          format: date-time
          description: The update date and time of the CarMake user's account.
        totalPRs:
          type: integer
          description: The total number of pull requests by the CarMake user.
        totalCommits:
          type: integer
          description: The total number of commits by the CarMake user.
        totalIssues:
          type: integer
          description: The total number of issues opened by the CarMake user.
        totalStars:
          type: integer
          description: The total number of stars received by the CarMake user's repositories.
        contributedTo:
          type: integer
          description: The number of repositories the CarMake user has contributed to.
        rank:
          $ref: '#/components/schemas/Rank'
        mostStarredBrands:
          type: array
          items:
            type: string
          description: List of the user's most starred repositories.

    Rank:
      type: object
      properties:
        level:
          type: string
          description: The level of the CarMake user's rank.
        percentile:
          type: number
          format: double
          description: The percentile of the CarMake user's rank.
    Repo:
      type: object
      properties:
        name:
          type: string
          description: The name of the brand's repository.
        full_name:
          type: string
          description: The full name of the brand's repository.
        private:
          type: boolean
          description: Indicates if the brand's repository is private.
        owner:
          type: object
          description: The owner of the brand's repository.
          properties:
            login:
              type: string
            type:
              type: string
            site_admin:
              type: boolean
        html_url:
          type: string
          description: The HTML URL of the brand's repository.
        description:
          type: string
          description: The description of the brand's repository.
        fork:
          type: boolean
          description: Indicates if the brand's repository is a fork.
        created_at:
          type: string
          format: date-time
          description: The creation time of the brand's repository.
        updated_at:
          type: string
          format: date-time
          description: The last update time of the brand's repository.
        pushed_at:
          type: string
          format: date-time
          description: The last push time of the brand's repository.
        homepage:
          type: string
          description: The homepage of the brand's repository.
        size:
          type: integer
          description: The size of the brand's repository.
        stargazers_count:
          type: integer
          description: The count of stargazers of the brand's repository.
        watchers_count:
          type: integer
          description: The count of watchers of the brand's repository.
        language:
          type: string
          description: The primary language of the brand's repository.
        has_issues:
          type: boolean
          description: Indicates if the brand's repository has issues enabled.
        has_projects:
          type: boolean
          description: Indicates if the brand's repository has projects enabled.
        has_downloads:
          type: boolean
          description: Indicates if the brand's repository has downloads enabled.
        has_wiki:
          type: boolean
          description: Indicates if the brand's repository has wiki enabled.
        has_pages:
          type: boolean
          description: Indicates if the brand's repository has CarMake pages enabled.
        has_discussions:
          type: boolean
          description: Indicates if the brand's repository has discussions enabled.
        forks_count:
          type: integer
          description: The count of forks of the brand's repository.
        mirror_url:
          type: string
          description: The mirror URL of the brand's repository.
        archived:
          type: boolean
          description: Indicates if the brand's repository is archived.
        disabled:
          type: boolean
          description: Indicates if the brand's repository is disabled.
        open_issues_count:
          type: integer
          description: The count of open issues in the brand's repository.
        license:
          type: object
          description: The license of the brand's repository.
          properties:
            key:
              type: string
            name:
              type: string
            spdx_id:
              type: string
            url:
              type: string
            node_id:
              type: string
        allow_forking:
          type: boolean
          description: Indicates if forking is allowed for the brand's repository.
        is_template:
          type: boolean
          description: Indicates if the brand's repository is a template.
        topics:
          type: array
          items:
            type: string
          description: The topics of the brand's repository.
        visibility:
          type: string
          description: The visibility of the brand's repository.
        forks:
          type: integer
          description: The number of forks of the brand's repository.
        open_issues:
          type: integer
          description: The number of open issues in the brand's repository.
        watchers:
          type: integer
          description: The number of watchers of the brand's repository.
        default_branch:
          type: string
          description: The default branch of the brand's repository.
        network_count:
          type: integer
          description: The network count of the brand's repository.
        subscribers_count:
          type: integer
          description: The subscribers count of the brand's repository.
        stargazerData:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date-time
              count:
                type: integer
              tag:
                type: string
        readme:
          type: string
          description: The README of the brand's repository.
